# Generated by Django 5.2.4 on 2025-08-06 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_birthday_year_user_role_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
