# Generated by Django 5.2.4 on 2025-08-06 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_user_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='display_name',
        ),
    ]
